version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: my_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database_name
      MYSQL_USER: your_mysql_username
      MYSQL_PASSWORD: your_mysql_user_password

volumes:
  mongodb_data: {}
