version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: CPDS_mongo
      MONGO_INITDB_ROOT_PASSWORD: cfz021024
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: my_redis
    command: ["redis-server", "--requirepass", "cfz021024"]   # Use the custom configuration
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro   # Mount the configuration file as read-only


  mysql:
    image: mysql:latest
    container_name: my_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cfz021024
      MYSQL_DATABASE: CPDS
      MYSQL_USER: Fengzc
      MYSQL_PASSWORD: cfz021024

volumes:
  mongodb_data: {}
