version: '3'
services:
  app:
    image: myapp
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - mongodb
      - redis

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dachuang

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=dachuang

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=
      - REDIS_DB=0
